title: 현업 SW 개발자의 연구 노트
description: 정보 비망록
show_downloads: false
google_analytics: G-95SGD9KQRE
theme: jekyll-theme-slate
markdown: kramdown
defaults:
  # _posts
  - scope:
      path: ""
      type: pages
    values:

