title: 현업 SW 개발자의 연구 노트
tagline: 정보 비망록
description: 정보 비망록
name: 현업 SW 개발자

favicon: "/assets/favicon.png"
favicon-invert: "/assets/favicon-invert.png"
image: "/assets/logo.png"

footer: false

google_analytics: G-95SGD9KQRE
theme: jekyll-theme-slate
markdown: kramdown

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-last-modified-at
  - jemoji

commenets:
  provider: "disqus"
  disqus:
    shortname: boyinblue-github-io

author:
  name: boyinblue
  picture: /assets/logo.png
  twitter: JisuPar18835589
  url: https://blog.naver.com/boyinblue

defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/logo.png"
      author: boyinblue

include:
  - _pages
