title: 현업 SW 개발자의 연구 노트
description: 정보 비망록
name: 현업 SW 개발자

logo: "/assets/logo.png"
favicon: "/assets/favicon.png"
image: "/assets/logo.png"

show_downloads: false
footer: false

google_analytics: G-95SGD9KQRE
theme: jekyll-theme-slate
markdown: kramdown

commenets:
  provider: "disqus"
  disqus:
    shortname: boyinblue-github-io

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

author:
  twitter: JisuPar18835589

defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/logo.png"

include:
  - _pages